### ISSUE TITLE
Compatibilità "Lettere" Vecchio PEM

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#100]
E' possibile in fase di inserimento di un emendamento, fatto con il nuovo PEM, valorizzare il campo testo "lettera" presente nel db con il text presente nella combobox utilizzata per selezionare la lettera?
Se possibile, dovrebbe venire preservata la compatibilità con la vecchia versione di PEM

**Comment by matteocattapan** [comment]
Si può fare

**Comment by ConsiglioRegionaleLombardia** [comment]
> Si può fare

Ok perfetto. Bisogna però prima verificare come fa PEM nuovo a gestire correttamente i metadati inseriti con il PEM vecchio. Ho verificato che se apro un em inserito dal vecchio pem (senza lettere codificate) il nuovo pem gestisce il tutto correttamente. Bisogna evitare che la modifica impatti sulla funzionalità attualmente corretta.
