### ISSUE TITLE
Permission denied su Stampe

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#102]
Dopo aver lanciato una stampa, il file pdf viene correttamente generato nella cartella Stampe ma il client non è in grado di recuperarla. Restituisce l'errore "access denied"

**Comment by matteocattapan** [comment]
L'errore è generato dal servizio "genera stampe" che per elaborare i documenti si serve di una cartella temporanea (parametro 
 configurabile nel job).
La cartella temporanea non ha i permessi dell'utente IIS_IUSRS, quindi il file che viene generato eredita i permessi della cartella, quindi senza il permesso a IIS_IUSRS.
Nel momento in cui il file generato viene spostato nella cartella "stampe" (contenitore di tutte le stampe), poi l'api non accede al file perchè l'utente IIS_USRS non ha i permessi di accedere a quel singolo file.
La soluzione più veloce è dare i permessi all'utente IIS_USRS in lettura/scrittura anche della cartella temporanea.
