### ISSUE TITLE
FILTRI: banner di spiegazione per ricerca sui documenti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1036]
Si chiede di inserire un banner che dia informazioni su come usare la ricerca dei documenti

**Comment by matteocattapan** [comment]
Cosa dobbiamo mettere nelle informazioni?

**Comment by ConsiglioRegionaleLombardia** [comment]
Informazioni
"La ricerca verifica la presenza o meno di un allegato: seleziona una o più tipologie per ricercare gli atti dove è presente l'allegato della tipologia selezionata. Spuntando "Cerca allegati mancanti" verranno estratti gli atti dove non sono stati caricati documenti della tipologia selezionata"
