### ISSUE TITLE
Ordinamento PDL in gestione sedute

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#104]
Tentando di ordinare i PDL nella gestione sedute viene restituito un errore
![image](https://user-images.githubusercontent.com/57402160/138075961-8346e9c5-14cd-44be-ae36-0609baa10f09.png)

**Comment by matteocattapan** [comment]
Mancavano le store DOWN_ATTO e UP_ATTO
