### ISSUE TITLE
Griglia: reset colonne dopo report

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1040]
Dopo aver selezionato un report precedentemente salvato, la griglia perde le colonne impostate e ritorna alla visualizzazione base (Dispaly + strumenti)

**Comment by matteocattapan** [comment]
Verificare in fase di review se si verifica ancora questo problema, perchè in debug non si verifica
![Image](https://github.com/user-attachments/assets/27861fd1-4a1d-4c71-ae77-c546d1972a33)
