### ISSUE TITLE
Report: gestione visualizzazione campo Emendato

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1043]
Il campo Emendato deve essere visualizzato solo sugli atti che vengono votati e possono essere approvati con modifiche (MOZ, ODG, RIS) mentre non deve apparire per gli altri atti a prescindere se è valorizzato a "Si" oppure a "No".
Nei report dove sono presenti sia ITL, ITR, IQT sia RIS, MOZ, ODG occorre verificare una possibile gestione di questo campo. Si potrebbe utilizzare il valore null per non farlo visualizzare.

**Comment by matteocattapan** [comment]
PROPOSTA:
Creare 2 report

- Configurare il report AA per IQT, MOZ, ODG abilitando la colonna "Emendato"
- Configurare il report BB per ITL, ITR disabilitando la colonna "Emendato"

In questo modo si usa correttamente la configurazione del report. Stessa cosa si può gestire con dei template separati.

**Comment by ConsiglioRegionaleLombardia** [comment]
Sentita UOLA, la soluzione migliore è quella proposta durante il SAL ovvero non visualizzare, nella visualizzazione a LISTA, il campo emendato se valorizzato a No.
L'ordinamento degli atti potrebbe cambiare in futuro e, qualora fosse necessario ordinarli cronologicamente, potrebbero dover apparire "mischiati": IQT, MOZ. ITL, MOZ, ODG, ITR, ecc

**Comment by ConsiglioRegionaleLombardia** [comment]
Corretta una svista nel testo del task: le IQT non sono emendabili
