### ISSUE TITLE
Report: aggiunta campo "Tipo risposta fornita"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1045]
Si chiede di aggiungere il campo "Tipo risposta fornita" speculare a "Tipo risposta richiesta" selezionabile nei report.
Il campo deve contenere solo il tipo di risposta fornita (scritta, orale o in commissione). Serve per raffrontare velocemente le risposte chieste dai consiglieri e quelle realmente fornite.

Si chiede la stessa nomenclatura anche per il filtro (si veda altro ticket)

**Comment by matteocattapan** [comment]
![Image](https://github.com/user-attachments/assets/f84064d8-fde3-4449-9d04-fcb1c65ce7b1)
Sono già presenti entrambi filtri vedi 
#1046
