### ISSUE TITLE
Filtri: rinominare il filtro "risposta"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1046]
Si chiede di rinominare il filtro "Risposta" in "Tipo risposta richiesta"

**Comment by matteocattapan** [comment]
![Image](https://github.com/user-attachments/assets/4d9d7f1c-3768-4ac6-aa3f-7d1664f50e90)
Ci sono già entrambi i filtri richiesti

**Comment by ConsiglioRegionaleLombardia** [comment]
E' vero: in effetti c'è un refuso nella richiesta. 
La specifica corretta è 
Risposta --> Tipo risposta fornita

Apriamo un nuovo ticket con la specifica giusta.
