### ISSUE TITLE
Report: aggiunta campo "Di iniziativa"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1047]
Si chiede di aggiungere il campo "Di iniziativa" tra quelli selezionabili nei report.
Il campo dovrà contenere in ordine, tutti i firmatari dell'atto, compreso il proponente, con il relativo gruppo di appartenenza.
es.
**Consigliere 1 (PD)**, Consigliere 2 (PD), Consigliere 3 (LEGA), ....

**Comment by matteocattapan** [comment]
Con le firme ritirate o senza?
