### ISSUE TITLE
Griglia: modifica colonne selezionabili

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1052]
Nella selezione delle colonne da visualizzare in griglia, rispetto a GEASI mancano le seguenti voci:
- Legislatura
- N° gg di ritardo, calcolato come Data risposta - Data Annunzio + 20 giorni. SE Data risposta è vuoto allora è calcolato come Oggi - Data Annunzio + 20 giorni (se, in entrambi i casi, il risultato è minore di 0 restituisce 0)
- Tipo risposta fornita (deve avere solo i valori: Scritta | Orale | In commissione)
- Data trasmissione RIS (è la data in cui la commissione trasmette la RIS all’assemblea per l’iscrizione in seduta. in GEASI corrisponde al campo Data Trasmissione presente nel TAB "Trattazione in commissione" che compare solo nelle RIS)

Non sono invece necessarie le seguenti colonne, che possono essere tolte:
- Tutte le voci relative ai "tipi di privacy" o "divieti di pubblicazione". Serve solo la voce "Privacy" ovvero il flag che indica se un atto ha problemi di privacy a prescindere dal motivo, come indicato nel ticket #995
- LINK pubblico (che attualmente corrisponde a un GUID non cliccabile)

L'elenco completo è nel ticket #989

**Comment by matteocattapan** [comment]
Tipo risposta fornita (deve avere solo i valori: Scritta | Orale | In commissione)
per le mozioni ci sono anche Iter in assemblea e Iter in assemblea + commissione
