### ISSUE TITLE
CRUD: RIS - Pannelli

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1064]
Per le Risoluzioni vanno tolti i pannelli "Chiusura Iter" e "Trattazione".
Vanno aggiunti i pannelli "Trattazione in comissione" e "Trattazione in assemblea"

**Comment by ConsiglioRegionaleLombardia** [comment]
![image](https://github.com/user-attachments/assets/95d85a08-1872-4620-821d-e4ac11bdf2f8)

**Comment by ConsiglioRegionaleLombardia** [comment]
![image](https://github.com/user-attachments/assets/84842916-ec71-4a30-82ed-95b09473f289)
NOTA: L'unico stato possibile selezionabile in "Trattazione in commissione" è Approvato

Per la "Trattazione in Assemblea" invece è possibile selezionare tutti gli stati

![image](https://github.com/user-attachments/assets/115cb24f-35e3-4e14-ac9e-b217293efcb7)


![image](https://github.com/user-attachments/assets/37505a6a-47af-4323-84e7-9edd60c8de13)

![image](https://github.com/user-attachments/assets/f8844a8b-288b-430f-b4d7-a81dc0015ea5)
**ATTENZIONE**: "Atto respinto" significa che l'atto è stato votato e respinto dall'assemblea. Ma non è la stessa funzionalità del bottone "RESPINGI". Selezionando "Atto respinto" si possono solo inserire i relativi dati (nella parte "Trattazione in commissione" non succede nulla)

![image](https://github.com/user-attachments/assets/01105925-597c-4238-af95-3473af3c3cb2)

![image](https://github.com/user-attachments/assets/defb906b-e3d3-4463-a549-9640c5f5891c)

![image](https://github.com/user-attachments/assets/da7bb052-2baf-435f-9165-d06b86f5952f)

**Comment by ConsiglioRegionaleLombardia** [comment]
**NOTA ESPLICATIVA:**
Con "Atto respinto" nel pannello "Trattazione in assemblea" significa che la RIS è stata votata ma non approvata dell’Assemblea: l'atto viene chiuso con uno stato "non approvato".

L'attuale tasto RESPINGI di GEASI, significa in realtà "ri-Trasmetti alla commissione”.
Premendo RESPINGI la RIS viene rimandata in commissione per un riesame. Premendo RESPINGI la parte "Trattazione in assemblea" si blocca mentre si sblocca la parte "Trattazione in Commissione". 
Qualora la commissione approvasse la RIS, nel secondo passaggio, la RIS verrebbe definitivamente approvata, senza la necessità di un ulteriore voto in assemblea e prenderebbe il numero di DCCR.
In questo caso i dati relativi alla trattazione in commissione verrebbero sovrascritti con i nuovi dati

Il tasto "RESPINGI", che sarebbe meglio sostituire con "RI-TRASMETTI IN COMMISSIONE" serve per rimandare/riassegnare l'atto alla Commissione:
![image](https://github.com/user-attachments/assets/99e6cd65-352b-4d95-8b41-0e7525acc85e)


Se si preme SI:
![image](https://github.com/user-attachments/assets/ced7a422-4952-4574-97a0-6f730fc78e65)

Dopo aver premuti SI, il menù a tendina "Tipo chiusura" presente in "Trattazione in commissione" si sblocca per poter inserire un "Tipo di chiusura" diverso (es. atto respinto in commissione, atto approvato, ecc).

Qualora l'atto venga approvato nuovamente in commissione, deve essere possibile inserire i dati della DCCR
![image](https://github.com/user-attachments/assets/90fff9fa-afdb-46ff-a358-350999b5044b)
Si perdono quindi i dati della prima approvazione in commissione

Probabilmente è quindi necessario un flag che indichi se l'atto è stato ritrasmesso in commissione.

I due testi, sia quello trasmesso all'aula in prima analisi, sia l'eventuale DCCR approvata rimangono memorizzati nel sistema. Ci sarà quindi da prevedere un ulteriore "tipo di documento" (es. CHIUSURA_ITER_RIS_COMMISSIONE)

Qualora venga premuto respingi (RI-TRASMETTI IN COMMISSIONE) una nota privata viene aggiunta dal sistema "Risoluzione riinviata in commissione il ________"

**Comment by matteocattapan** [comment]
Migrato in ticket #1151
