### ISSUE TITLE
CRUD: MOZ, ODG, RIS - Pannello "Monitoraggio"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1067]
Nel pannello monitoraggio mancano i seguenti campi:
- Data trasmissione (da aggiungere come colonna alla tabella Organi Monitoraggio)
- Altri soggetti (sarebbe da aggiungere alla tabella): in pratica è un organo che effettua il monitoraggio che non è di Giunta e neanche una Commissione

![image](https://github.com/user-attachments/assets/4fc2b7f1-8117-472c-9d1d-62b790bfd789)

- Competenza
- Impegni e scadenze
- Stato attuazione
- Concluso (SI/NO)
- Documenti monitoraggio

**Comment by ConsiglioRegionaleLombardia** [comment]
![image](https://github.com/user-attachments/assets/e1176ad3-2a03-4fc2-bb86-7c4114442db2)

**Comment by matteocattapan** [comment]
![Image](https://github.com/user-attachments/assets/35e6377a-0723-47e4-86be-0729ec7febfa)
Altri soggetti: già presente
Data trasmissione: campo presente nell'excel, ma NON IMPORTATO
Competenza: da aggiungere nella ui
Impegni e scadenze: da aggiungere nella ui
Stato attuazione: da aggiungere nella ui
Documenti monitoraggio: già presente
Concluso: campo presente nell'excel, ma NON IMPORTATO

**Comment by ConsiglioRegionaleLombardia** [comment]
Per la data_trasmissione attendere un chiarimento con UOLA: in GEASI è un campo unico ma a logica sembrerebbe legato per 
Per quanto riguarda Altri soggetti, si tratta di altri soggetti che effettuano il monitoraggio: logicamente sono come le Commissioni o la Giunta. Se con l'attuale struttura di database non è possibile inserirli insieme a Giunta e Commissioni è meglio spostare il campo sotto la tabella degli altri organi e, come in GEASI, racchiudere tabella e altri soggetti in un DIV:
![image](https://github.com/user-attachments/assets/85b72304-3feb-42fb-a114-4626b2e02b9a)


E' importante che "impegni e scadenze" accetti grassetto, sottolineato e italic

**Comment by ConsiglioRegionaleLombardia** [comment]
Si conferma che data_trasmissione è un unico campo e può quindi essere trattato come in GEASI
