### ISSUE TITLE
Export excel non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1074]
L'esportazione rapida Excel non è più funzionante: il file non viene generato

**Comment by matteocattapan** [comment]
Ho provato oggi e funziona.
Sentiamoci e capiamo perchè va in errore

**Comment by ConsiglioRegionaleLombardia** [comment]
Probabilmente è un problema relativo a qualche dato "sporco".
Con il filtro "XI" e "MOZ, ODG, RIS" viene visualizzato questo errore:
![image](https://github.com/user-attachments/assets/a50189a0-1f9c-4f9e-9dba-f7437ad2f0cb)
