### ISSUE TITLE
Griglia: Bottone per attivazione dell'ordinamento

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1081]
Verificare se è possibile spostare nei filtri oppure nell'intestazione della griglia (ultima colonna) la funzione di ordinamento 
![image](https://github.com/user-attachments/assets/95065864-7b62-4bab-9c60-af5ce7accdf5)

Se viene spostato nei filtri il "nome ricercabile" potrebbe essere Ordinamento

**Comment by matteocattapan** [comment]
Vedi #1080
