### ISSUE TITLE
Filtri: filtro per range di date

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1082]
Qualora sia stata impostata solo la data DAL, si chiede di effettuare il filtro per range di date dalla data inserita in poi (fino a oggi)

![image](https://github.com/user-attachments/assets/9156a717-0544-444a-aff2-a3b386870377)

Esempio:
Se filtro DAL 1/1/2025 al __________
il risultato deve portare tutti gli atti iscritti **dalla** seduta del 1/1/2025 fino ad oggi ovvero data_seduta >= campo_DAL

**Comment by matteocattapan** [comment]
Per fare questo basta indicare la data "A" con la data odierna. Non è necessario cambiare il comportamento del filtro.

Il comportamento dei range di date è questo:
 - data singola
 - range

Quindi per effettuare una ricerca per data precisa basta inserire la data nel campo DA.
Nel caso si voglia effettuare una ricerca per range bisogna inserire DA e A

**Comment by matteocattapan** [comment]
E' già stata verificata durante il collaudo la funzionalità
