### ISSUE TITLE
Report: eliminazione di un report non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1092]
I report vengono cancellati solo apparentemente. Ad esempio non si riesce a cancellare uno dei due:
![image](https://github.com/user-attachments/assets/6466ad8b-2f35-49da-a5ea-a81ffe3f3ecf)

**Comment by matteocattapan** [comment]
![Image](https://github.com/user-attachments/assets/ddad9358-f930-4bdc-8857-b6a8814b191a)
Al momento non si verifica, da verificare

**Comment by ConsiglioRegionaleLombardia** [comment]
ricaricando la pagina il report eliminato è scomparso dall'elenco?

**Comment by matteocattapan** [comment]
si, quando viene eliminato un report, questo poi non viene più visualizzato
