### ISSUE TITLE
Report: Ordinamento colonne

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1093]
Le colonne nei report (ovvero i campi che vengono visualizzati negli estratti in pdf, word, excel) devono avere questo ordine di visualizzazione sia nel formato LISTA sia nel formato TABELLARE:
1	Legislatura
2	Etichetta	
3	Tipo atto	
4	Numero atto	
5	Tipo e numero atto	
6	Tipo e numero atto esteso	
7	Tipo mozione	
8	Oggetto	
9	Oggetto modificato _(potrebbe bastare oggetto se viene sovrascritto correttamente)_
9a.   Oggetto approvato _(dall'ultimo SAL parrebbe sia necessario)_
10	Data presentazione
11	Data annunzio	
12	Protocollo
13	Codice materia
14	Proponente	
15	Altri firmatari	
16	Di iniziativa _(ovvero tutti i firmatari)_
17	Conteggio firme
18	Gruppo politico
19	Area Politica
20	Commissioni proponenti	
21	Stato dell’atto
22	Motivo chiusura iter
23	DCR/DCCR	
24	Data seduta	
25	Data chiusura	
26	Data comunicazione assemblea
27	Data ritiro	
28	Tipo votazione
29	Emendato
30	Abbinamento	
31	Note	
32	Allegati dell’atto	
33	Tipo risposta richiesta	
34	Tipo risposta fornita
35	Informazioni risposte
36	Sollecito	
37	Iter multiplo	
38	Non passaggio in esame	
39	Presentato oltre i termini	
40	Pubblicato	
41	Premesse	
42	Richieste
43	Testo approvato _(premesse + richieste modificate: serve per generare le DCR. Potrebbero bastare solo Premesse e richieste se vengono generate con le corrette modifiche)_
44	Impegni e scadenze	
45	Stato attuazione	
46	Competenza monitoraggio	
47	Area Tematica
48	Altri soggetti
49	Privacy - dati giudiziari	
50	Privacy - dati sanitari	
51	Privacy - dati di natura sessuale	
52	Privacy - divieto di pubblicazione	
53	Privacy - dati sensibili	
54	Privacy - altri motivi	
55	Privacy - dati personali semplici	
56	Privacy
57	BURL 
58	QR code	
59	UIDAtto

**Comment by matteocattapan** [comment]
Servono tutti i campi privacy nei report oppure possiamo tenere solo 56 e 52?
E' corretto che il 56 sia in fondo alla lista? Il campo indica che uno degli altri campi che indicano il motivo di intervento per privacy è attivo (49/50/51/52/53/54/55)

**Comment by ConsiglioRegionaleLombardia** [comment]
Si possono tenere solo ili 52 e 56
Il 56 è meglio prima del 52

NOTA: Nei filtri invece vanno mantenuti tutti i flag privacy come indicato nel relativo ticket

**Comment by matteocattapan** [comment]
Non vengono trattati nella lista i seguenti campi:

- Informazioni monitoraggio
- MonitoraggioConcluso
- DataTrasmissioneMonitoraggio
- DataRichiestaIscrizioneSeduta
- DataIscrizioneSeduta

**Comment by ConsiglioRegionaleLombardia** [comment]
- Informazioni monitoraggio (mantenere in posizione 49)
- MonitoraggioConcluso (mantenere in posizione 50)
- DataTrasmissioneMonitoraggio (mantenere in posizione 51)
- DataRichiestaIscrizioneSeduta - TOGLIERE
- DataIscrizioneSeduta - TOGLIERE
