### ISSUE TITLE
Report: Interlinea nei report a LISTA in word

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1094]
Verificare se è possibile togliere la spaziatura (interlinea) tra un campo e l'altro nella visualizzazione dei report/estratti in word

**Comment by matteocattapan** [comment]
Quale interlinea ti riferisci?

**Comment by ConsiglioRegionaleLombardia** [comment]
Quella di word tra un campo e l'altro. Ora stampa così:

**Tipo atto**: ITL

**Numero atto**: 1023

**Firmatari**: Pippo

**Informazioni risposta**: Scritta: Assessore al welfare


**Data trasmissione Aula**: 20/2/2002
