### ISSUE TITLE
CRUD: Priorità e firme su atti chiusi

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1103]
Nascondere la funzionalità di gestione delle priorità e di ordinamento firme sugli atti chiusi:
![image](https://github.com/user-attachments/assets/511912bb-a8fa-42c1-ae16-d50889448728)

**Comment by ConsiglioRegionaleLombardia** [comment]
Per agire sulle firme dopo la chiusura di un atto, l'atto dovrà essere riportato in uno stato di TRATTAZIONE o PRESENTAZIONE

**Comment by matteocattapan** [comment]
Valutare se mettere blocco se l'atto è stato protocollato. In ogni caso solo per UOLA.

**Comment by ConsiglioRegionaleLombardia** [comment]
Concordo, è una soluzione migliore
