### ISSUE TITLE
CRUD: Automatismi

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1110]
Si chiede di prevedere i seguenti automatismi durante l'inserimento dati

-	**Per tutti gli atti:** inserendo la data di annunzio lo stato da “presentato” cambia in “in trattazione”
-  **Per MOZ, ODG, RIS:** Inserendo il "Motivo di chiusura" lo stato dell'atto passa a CHIUSO
-	**Per le IQT:** inserendo la data di risposta della IQT, nella maschera relativa alle informazioni di risposta, se nel pannello "Chiusura iter" si sceglie “Trattazione in assemblea”  in automatico la data di chiusura si auto-compila con la data di risposta

**Comment by ConsiglioRegionaleLombardia** [comment]
Si chiede di aggiungere questo automatismo: se un atto è CHIUSO, nel momento in cui lo "riapro" (metto in Presentato o in Trattazione), il sistema deve cancellare le Motivazioni di chiusura e le informazioni correlate.

**Comment by ConsiglioRegionaleLombardia** [comment]
Ulteriori automatismi da valutare:
Quando un atto non è stato approvato (quindi per tutti gli altri motivi di chiusura), la tab monitoraggio è disabilitata. 
Quando un atto è chiuso al salvataggio viene visualizzato l'alert "Stai modificando un atto chiuso. Procedere?"

**Comment by matteocattapan** [comment]
Dividere la richiesta in altri task perfavore
