### ISSUE TITLE
CRUD: errore in cambio stato nei comandi massivi

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1119]
Cambiando massivamente lo stato di alcuni atti, viene restituito un errore:
![image](https://github.com/user-attachments/assets/dab5bc65-f464-4bed-9c59-7eebc4190835)

E' stato testato il cambio stato massivo da PRESENTATO a CHIUUSO  di 3 RIS

**Comment by matteocattapan** [comment]
Sembra funzionare in debug, aspettiamo la review per capire se effettivamente vada in errore
