### ISSUE TITLE
Campo oggetto - sola lettura

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1124]
Il campo oggetto non è più corretto che sia in sola lettura, lasciando la gestione solo nella griglia?

In caso affermativo: spostare l'oggetto come primo dato visualizzato nella scheda Informazioni Generali e visualizzarlo come label o comunque non modificabile. Le modifiche agli oggetti vanno fatte dalla griglia

![image](https://github.com/user-attachments/assets/33432d2b-4ce3-4bee-a6bc-93cb5cfed03b)

**Comment by matteocattapan** [comment]
#1147
