### ISSUE TITLE
Griglia: ordinamento risultati griglia

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1133]
Aggiungere la possibilità di ordinamento per
Legislatura
Numero atto
Data annunzio
Data seduta
Data comunicazione all’assemblea

![image](https://github.com/user-attachments/assets/f2d1f888-c63d-41f0-9862-e23e34cb4d1f)

**Comment by ConsiglioRegionaleLombardia** [comment]
Se possibile mettere il menu a tendina con questo ordine:
Legislatura
Tipo atto
Numero atto
Data presentazione
Data annunzio
Data seduta
Dcr/Dccr
Data comunicazione all’assemblea

**Comment by matteocattapan** [comment]
Non è possibile ordinare per data seduta (difficile ordinare per guid)
