### ISSUE TITLE
Griglia: calcolo pagine errato

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1138]
Il calcolo delle pagine non funziona correttamente:
![image](https://github.com/user-attachments/assets/a2cab6c4-9fc0-4480-b169-b5f507410149)
153 risultato stanno infatti in 7 pagine da 20 elementi e non in 8

Questo problema comporta che arrivando sull'ultima pagina ci si ritrova bloccati

**Comment by matteocattapan** [comment]
Per calcolare le pagine bisogna fare il totale di risultati diviso il taglio di pagina:
153/20 = 7.65 che viene correttamente arrotondato ad 8. Infatti 7*20 fa 140, quindi in 7 pagine non sarebbe possibile rappresentare 153 risultati.

**Comment by ConsiglioRegionaleLombardia** [comment]
Giusto, avevo calcolato male. Tuttavia l'ultima pagina, l'ottava, non presenta atti e quindi la paginazione scompare bloccando la navigazione

**Comment by matteocattapan** [comment]
![image](https://github.com/user-attachments/assets/0b55105a-16be-41f3-8eb8-dc0367aa2546)
Non mi sembra, probabile che stai applicando un filtro particolare?

**Comment by ConsiglioRegionaleLombardia** [comment]
**ATTENZIONE**: Mi raccomando le TEMP. Non devono essere viste da UOLA fino al deposito

**Comment by matteocattapan** [comment]
Risolto anche il bug sul filtro per UOLA
