### ISSUE TITLE
CRUD: Grafica "elimina riga" nelle tabelle

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1152]
Si chiede, per differenziare i due tipi di eliminazione presenti nelle tabelle, lasciando la x per l'eliminazione di un'informazione presente nelle colonne (es. files caricato) e inserendo un'icona cestino quando si elimina una riga intera:
![image](https://github.com/user-attachments/assets/6ac08249-61f9-4fbe-afc2-5571ca07ba3a)

**Comment by matteocattapan** [comment]
vedi #1150
