### ISSUE TITLE
CRUD: Aggiunta risposta

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1158]
Dopo aver caricato una risposta, la pagina si aggiorna e occorre tornare nella TAB informazioni risposte per poter proseguire con l'inserimento dati. Il comportamento corretto è quello di aggiornare solo la tabella caricando i nuovi dati (come accade per le note)

**Comment by matteocattapan** [comment]
vedi #1153
