### ISSUE TITLE
Griglia: iscrizione di un atto in seduta

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1166]
La funzionalità per iscrivere un atto in una seduta pare non funzioni:
![image](https://github.com/user-attachments/assets/ed6b0b8b-06ef-402b-a201-47ec129e4da0)

**Comment by matteocattapan** [comment]
[#1160](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/issues/1160)
