### ISSUE TITLE
Report-Griglia: Visualizzazione ordinamenti dopo la selezione di un report

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1172]
Dopo aver selezionato un report che contiene abbinamenti, gli stessi non vengono visualizzati nella parte dedicata ai filtri:
![image](https://github.com/user-attachments/assets/3a1ab566-613e-40bb-9043-d63931097e3c)

**Comment by ConsiglioRegionaleLombardia** [comment]
Per la visualizzazione dei chips relativi all'ordinamento, verrebbe più pulito visualizzarli sotto i filtri (vedi #1163)

Sarebbe possibile visualizzare l'ordinamento in un'unica chip?

> **Ordinato per Tipo atto Crescente, Numero atto Crescente**

**Comment by matteocattapan** [comment]
Stai facendo 3 richieste in 1, come devo procedere?

**Comment by ConsiglioRegionaleLombardia** [comment]
Ok. Da considerare solo la issue che è più un bug.
Per la parte puramente grafica (messa nel commento) apro un nuovo issue
