### ISSUE TITLE
Report: report "Conteggio risposte Atti ispettivi" non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#1197]
Rivedere il formato grafico, l'impaginazione e il calcolo delle percentuali del report non configurabile "Conteggio risposte Atti ispettivi".

**Comment by ConsiglioRegionaleLombardia** [comment]
Deve esserci una altro task aperto su questo report ma non riesco a trovarlo per collegarlo

**Comment by matteocattapan** [comment]
[#1017](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/issues/1017)
Questo?

**Comment by ConsiglioRegionaleLombardia** [comment]
Si
