### ISSUE TITLE
CRUD: RIS salvataggio trattazione in commissione

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#1214]
![Image](https://github.com/user-attachments/assets/750ce2c6-3dac-4905-965e-6c9794675ffd)

Tipochiusuraiter e risultato votazione vanno bloccati e non salvati.
Abilitare il salvataggio solo di data chiusura iter commissione e data trasmissione.

**Comment by ConsiglioRegionaleLombardia** [comment]
Solo Tipo chiusura iter è bloccato su "approvato"
