### ISSUE TITLE
Grafica Preview

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#158]
Nella preview il numero dell'EM rimane a sinistra anzichè centrato

**Comment by matteocattapan** [comment]
![image](https://user-images.githubusercontent.com/75838323/140092139-d888378f-99c4-4a83-9fa4-0751c7bac4a8.png)

**Comment by matteocattapan** [comment]
Sembra sia risolto, probabilmente doveva liberare la cache
