### ISSUE TITLE
URGENTE: Selezione memorizzata (ed errata) dopo un'operazione

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#172]
Dopo aver selezionato degli em dalla griglia ed aver effettuato una firma rimane A VIDEO la selezione precedentemente effettuata (va tolta) ma IN MEMORIA la selezione è errata, infatti, provando a effettuare subito dopo un deposito il sistema tenta di depositare tutti gli emendamenti del gruppo politico (26 nell'esempio).
PROBLEMA CON PRIORITA' ALTA
![image](https://user-images.githubusercontent.com/57402160/140735712-4f6b7bdc-220a-48f3-9327-cb6cb1035568.png)

**Comment by matteocattapan** [comment]
Vedi #171
