### ISSUE TITLE
Estrazione Excel - Link pubblico non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#203]
Dal file excel, tentando di accedere al link pubblico dell'emendamento viene richiesta l'autenticazione (non deve essere richiesta)
![image](https://user-images.githubusercontent.com/57402160/145559272-1648c30c-6cac-484c-ac8f-470c58734722.png)
Dopo essersi autenticati l'applicazione va in errore:
![image](https://user-images.githubusercontent.com/57402160/145559390-d799898d-4f8c-46cc-9c64-ce0a9ae670be.png)

**Comment by matteocattapan** [comment]
Risolto in precedente commit #201
