### ISSUE TITLE
DURANTE LA DISCUSSIONE IN AULA IL TESTO E' STATO COSI' MODIFICATO

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#21]
In visualizzazione preview, su tutti gli EM compare la funzionalità "DURANTE LA DISCUSSIONE IN AULA IL TESTO E' STATO COSI' MODIFICATO:"

**Comment by matteocattapan** [comment]
Verificare se con i nuovi aggiornamenti il problema persiste. Al momento in sviluppo il bug non è presente.

**Comment by ConsiglioRegionaleLombardia** [comment]
> Verificare se con i nuovi aggiornamenti il problema persiste. Al momento in sviluppo il bug non è presente.

Ok, appena pronto l'aggiornamento installo e verifico
