### ISSUE TITLE
Ritiro EM dopo inizio seduta

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#222]
Dopo l'inizio della seduta il consigliere può ancora ritirare un emendamento. Dopo le ultime modifiche evolutive questo non deve essere possibile: deve apparire il messaggio che chiede di contattare la Segreteria dell'Assemblea per effettuare il ritiro (vedere PEM v.1)

**Comment by matteocattapan** [comment]
![image](https://user-images.githubusercontent.com/75838323/167255296-4bb7b358-4070-48ce-9cac-8fa39dee225a.png)
