### ISSUE TITLE
Vulnerability SharpZipLib

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#223]
Verificare la possibilità di aggiornare la libreria che presenta una vulnerabilità

**Comment by matteocattapan** [comment]
Puoi darmi più info su dove trovare la vulnerabilità?

**Comment by ConsiglioRegionaleLombardia** [comment]
La segnala sull'homepage github di pem.
Dice di passare dalla versione 1.2 alla 1.3.3 che risolve la vulnerabilità.
Domani se non hai trovato ti mando lo screenshot



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Matteo Cattapan ***@***.***>
Data: 21/03/22 17:54 (GMT+01:00)
A: Consiglio-Regionale-della-Lombardia/PEM ***@***.***>
Cc: Pagliaro Massimiliano ***@***.***>, Author ***@***.***>
Oggetto: Re: [Consiglio-Regionale-della-Lombardia/PEM] Vulnerability SharpZipLib (Issue #223)


Puoi darmi più info su dove trovare la vulnerabilità?
