### ISSUE TITLE
DASI: Parametri di ricerca

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#256]
Aggiungere agli attuali parametri di ricerca anche i campi:
- TIPO RISPOSTA
- DATA PRESENTAZIONE DA_________       DATA PRESENTAZIONE A_________ (può essere vuoto) /Va aggiunto un campo a db (data_search)
- DATA SEDUTA
- N. ATTO DAL_______        N.ATTO AL _____    / va aggiunto un campo a db (n_atto_search)

**Comment by matteocattapan** [comment]
Aggiunto full-text
