### ISSUE TITLE
Export Word (tabella)

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#26]
L'esportazione dell'elenco degli emendamenti in word lascia i tag html che rendono il testo poco leggibile

**Comment by matteocattapan** [comment]
Replace 
&nbsp; => " "

**Comment by matteocattapan** [comment]
& n b s p ;

**Comment by ConsiglioRegionaleLombardia** [comment]
Qualche tag è rimasto... facciamo una verifica per capire il motivo?

**Comment by matteocattapan** [comment]
https://github.com/onizet/html2openxml

**Comment by ConsiglioRegionaleLombardia** [comment]
> https://github.com/onizet/html2openxml

Non sembra male. Basta citarlo in documentazione.

**Comment by matteocattapan** [comment]
[PEM_12072021_111319.docx](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/files/6800109/PEM_12072021_111319.docx)
