### ISSUE TITLE
PEM: Errore inserimento PDL

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#279]
Durante l'inserimento del PDL230 nella seduta del 26/07/2022 l'atto si è duplicato e si sono inseriti 3 pdl 230.
Sono stati cancellati gli altri due per procedere coi lavori. Ma si sono riduplicati dopo una modifica al pdl. Cancellati di nuovo.
E' necessaria una verifica. Si può controllare nel db la presenza di questi dati sporchi

**Comment by matteocattapan** [comment]
L'utente ha cliccato due o più volte sul tasto di salvataggio, come un "doppio click", escludendo problemi sull'api.
Risolvo correggendo l'evento lato client che gestisce il salvataggio.
