### ISSUE TITLE
Conteggio EM/SUBEM errato

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#28]
Dopo aver inserito un EM d'ufficio, il conteggio sul footer del PDL segnala un SUBEM anzichè un EM come in allgato
![image](https://user-images.githubusercontent.com/57402160/123615249-66703d80-d805-11eb-8e11-817c33d2f6ee.png)

**Comment by matteocattapan** [comment]
![image](https://user-images.githubusercontent.com/75838323/124238039-78f5ba00-db18-11eb-9267-43dc653e5623.png)
