### ISSUE TITLE
EVO: Aggiunta del metadato per indicare le parti modificate in leggi regionali attraverso pdl di modifica

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#304]
I pdl di modifica, ovvero quelli che modificano una legge regionale in vigore, creano confusione durante l’indicazione della parte da emendare e non permettono gestire correttamente l’ordinamento degli EM/SUBEM. Infatti, le lettere di questi pdl fanno riferimento a una o più parti della Legge regionale che modificano (es. la lettera b) del pdl prevede che la lettera k) di una L.R. sia modificata - vedasi pdl 36 seduta 19 febbraio 2019). Occorre quindi prevedere la possibilità di specificare, attraverso i metadati dell’EM/SUBEM, la parte della L.R. che viene modificata in modo da supportare e facilitare l’inserimento e permettere il corretto ordinamento.
La modifica richiesta prevedere di aggiungere un’ulteriore categoria emendabile denominata Parte_LR. Anche questa ulteriore parte sarà strutturata attraverso una tabella di supporto correlata alla nuova tabella delle lettere ovvero una Parte_LR si potrà collegare solo a una lettera e non a un articolo/comma.
Questa nuova funzionalità potrà essere attivata/disattivata dall’UOLA durante la predisposizione del PDL attraverso un flag denominato “PDL modificativo di Legge Regionale” (con modalità simile all’impostazione dei pdl di bilancio). Solo per questa tipologia di PDL, durante l’inserimento di un EM/SUBEM, dopo la selezione della lettera, verrà richiesto di inserire l’eventuale (non obbligatorio) Parte_LR.
La frase che verrà precompilata selezionando questo tipo di emendamento sarà “La [Parte_LR] di cui alla lettera x del comma x dell’articolo x è modificata come segue:”

**Comment by ConsiglioRegionaleLombardia** [comment]
Sostituita con le evolutive dei ticket #552 #553
