### ISSUE TITLE
EVO: Ricerca complessiva su tutti gli EM presenti in piattaforma

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#305]
Aggiungere una voce nel menu principale di PEM (banda laterale sinistra) che consenta la ricerca di EM/SUBEM sulla totalità degli EM/SUBEM presenti nella piattaforma con possibilità di filtrare anche per progetto di legge. (Es. cerca tutti gli EM/SUBEM con primo firmatario Fabio Pizzul)

**Comment by matteocattapan** [comment]
Probabilmente verrà sostituito da un'esportazione excel di tutti gli atti e gli emendamenti della legislatura corrente effettuali dal consigliere

**Comment by ConsiglioRegionaleLombardia** [comment]
Questa evolutiva non viene sviluppata. Sostituita con l'evolutiva del ticket #411
