### ISSUE TITLE
EVO: Inserimento guidato di emendamenti a partire dal testo del PDL

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#307]
Realizzare una funzionalità, in aggiunta all’attuale modalità di inserimento degli EM/SUBEM, che permetta di creare emendamenti posizionandosi col mouse direttamente sulla parte del PDL, visualizzato in anteprima a video. L’inserimento di emendamenti attraverso questo nuovo processo visuale e assistito consentirà di ridurre al minimo gli errori sulle parti del PDL che si intende emendare e sulla tipologia di emendamento (aggiuntivo, modificativo, soppressivo) nonché evitare l’utilizzo di versioni errate del PDL e il possibile inserimento di emendamenti multipli.
Prima di procedere dovrà essere predisposta una simulazione grafica.
Precondizioni: E’ richiesto lo sviluppo dei punti 8-10-11 e un opportuno lavoro di predisposizione delle parti emendabili in fase di creazione della seduta. E’ possibile tuttavia uno sviluppo con i soli estremi delle parti emendabili senza la presenza a video del relativo testo (articolo, comma, lettera, subParte_LR)

![image](https://user-images.githubusercontent.com/75838323/179718091-9b1f74b2-a3e1-4d51-b1a9-0fa6e6c0b1cf.png)

**Comment by ConsiglioRegionaleLombardia** [comment]
@EM-3: Trattandosi di una funzionalità che richiede molti inserimenti ripetitivi si chiede, se possibile e solo per questa funzionalità, di togliere il “messaggio di successo”

**Comment by ConsiglioRegionaleLombardia** [comment]
Funzionalità realizzata
