### ISSUE TITLE
Firma Relatore anche in griglia

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#31]
Si visualizza nel tooltip, ma non nella colonna "firme" la scritta "RELATORE"

**Comment by matteocattapan** [comment]
![image](https://user-images.githubusercontent.com/75838323/124487480-110cd100-ddaf-11eb-8464-6ba15d86b180.png)

**Comment by ConsiglioRegionaleLombardia** [comment]
Va bene la nuova modalità ma è da riportare anche per gli utenti dei gruppi
![image](https://user-images.githubusercontent.com/57402160/124895342-c07abb00-dfdc-11eb-8156-747f8fb99655.png)

**Comment by matteocattapan** [comment]
vedi pdl 168. Non viene visualizzato su quelli non fuori termine
