### ISSUE TITLE
Proietta

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#32]
Andando su proietta viene visualizzato l'errore nello screenshot
![image](https://user-images.githubusercontent.com/57402160/124440852-5fa07800-dd7b-11eb-982b-ecbde316ce56.png)

**Comment by matteocattapan** [comment]
Se non trova nessun em in proiezione, va in errore

**Comment by ConsiglioRegionaleLombardia** [comment]
Mi da ancora errore quando non c'è nessun em selezionato
![image](https://user-images.githubusercontent.com/57402160/124616686-960eed80-de76-11eb-906d-ea592b936726.png)

**Comment by matteocattapan** [comment]
Per risolvere il problema è necessario portare a "FALSE" il valore Proietta:

**update em set Proietta=0 where Proietta is null**

Dopodichè è possibile modificare la tabella EM impostando la colonna Proietta sempre valorizzata con default a "FALSE".
