### ISSUE TITLE
DASI: Visualizzazione e conteggio errati degli odg "in aula"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#345]
In visualizzazione aula vengono visualizzati anche gli ODG in bozza:
![image](https://user-images.githubusercontent.com/57402160/182120719-9de032bb-aee3-4c23-8ba0-a6180b48cfc7.png)

**Comment by matteocattapan** [comment]
fix #351
