### ISSUE TITLE
Firme in Griglia UOLA

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#35]
Se possibile mettere le firme nella griglia della segreteria dell'assem
![image](https://user-images.githubusercontent.com/57402160/124491159-40254180-ddb3-11eb-999a-a7434ebb2c5a.png)
blea come nella griglia responsive (vedi screenshot)

**Comment by matteocattapan** [comment]
Nella nuova visualizzazione è cambiata la grafica. Vuoi comunque modificarla con il numero?

**Comment by ConsiglioRegionaleLombardia** [comment]
Questa modalità mi piaceva (con l'indicazione del RELATORE qualora abbia firmato un relatore). Però visto che è cambiata la grafica possiamo tenere quella nuova

**Comment by matteocattapan** [comment]
Aggiungere contatore con chip
