### ISSUE TITLE
DASI: Errore BLOCCANTE negli inviti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#350]
Non è possibile effettuare un invito nelle MOZ:
![image](https://user-images.githubusercontent.com/57402160/182421520-6297e14f-79e1-41fe-8aab-15c6eb13f067.png)

NOTA: L'invito (e l'aggiunta di firme) deve essere possibile fino a quando UOLA non ha iscritto l'atto ad una seduta

**Comment by matteocattapan** [comment]
Quest'errore è dovuto al fatto che state inserendo lo stesso invitato.
Ecco, forse, sarebbe meglio scriverlo meglio il messaggio di errore..

**Comment by ConsiglioRegionaleLombardia** [comment]
OK. Meglio scrivere che: "Nome Cognome è già stato invitato per questo atto". Se non possibile mettere: "E' già presente un invito per una delle persone indicate". Attenzione però che a seguito dell'errore il sw deve continuare la procedura e mandare l'email.

**Comment by ConsiglioRegionaleLombardia** [comment]
L'errore, almeno sulle ITL, si verifica anche quando viene effettuato il primo invito (quindi non può essere stato selezionato lo stesso invitato). Verificato oggi
