### ISSUE TITLE
DASI: @ITR-50 - Stampa solo atti accessibili al gruppo 

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#378]
Non stampa gli Atti che compaiono a video e non stampa solo quelli del gruppo. STAMPA TUTTI GLI ATTI ANCHE QUELLI DI ALTRI GRUPPI: NELL’AREA PRIVATA DEL GRUPPO DEVONO ESSERE ACCESSIBILI SOLO GLI ATTI DEL GRUPPO.

**Comment by ConsiglioRegionaleLombardia** [comment]
Effettuata una prova filtrando ITR depositate e ancora vengono stampati gli atti di altri gruppi politici (PD + LEGA)
