### ISSUE TITLE
DASI: @ITR-139 - Modifica della commissione indicata da UOLA

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#385]
La modifica della commissione non viene memorizzata e sembra che venga sempre posto in modifica il primo atto della griglia

**Comment by ConsiglioRegionaleLombardia** [comment]
Ora viene correttamente preso in modifica-metadati l'atto selezionato ma comunque le modifiche non vengono memorizzate
