### ISSUE TITLE
Firma-Ritiro-Firma

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#43]
Nel caso in cui un consigliere tenti di firmare un emendamento sul quale ha precedentemente ritirato la firma, il sistema restituisce un errore tecnico di violazione "chiave primaria". Si chiede di sostituire il messaggio con il seguente: "Non è possibile firmare questo emendamento in quanto risulta presente una firma ritirata"
![image](https://user-images.githubusercontent.com/57402160/124780639-0e42e500-df43-11eb-88f8-1e84d310acf1.png)

**Comment by matteocattapan** [comment]
Firma massiva torna l'errore
