### ISSUE TITLE
DASI: ITR-131 - Ritiro ultima firma

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#436]
Il consigliere può ritirare la propria firma e se è l’ultima firma presente sull’atto, l’atto viene correttamente ritirato. Deve però poter anche ritirare l’atto attraverso la funzione “Ritira”: in questo caso l’atto risulta ritirato ma le firme non devono risultare ritirate

**Comment by ConsiglioRegionaleLombardia** [comment]
Effettuata una nuova prova su una ITR è possibile ritirare la firma ma non compare la funzionalità per ritirare tutto l'atto
