### ISSUE TITLE
DASI: ODG-41 - Selezionare atti di sedute attive aperte

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#439]
Gli atti iscritti in una seduta “non aperta” (ovvero la data
apertura seduta è futura) o già “chiusa”, non devono
apparire nella combobox che permette di selezionare
atti/argomenti durante l’inserimento degli ODG

**Comment by ConsiglioRegionaleLombardia** [comment]
Questo fix pare non funzioni correttamente (Effettuato un test impostando la RIS 59 con apertura 25/11/2022 17:00 tuttavia si vede lo stesso nell'inserimento di un ODG)
