### ISSUE TITLE
DASI: @IQT-6: "Inserimento di IQT (proposta seduta) solo nelle sedute non chiuse"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#449]
Per le IQT deve essere possibile selezionare come data “Proponi iscrizione seduta” tutte le date delle sedute non chiuse (**anche se non sono ancora aperte**: va quindi controllata solo la data di chiusura delle seduta che deve essere null o > Now()) e impostate come “Dedicata allo svolgimento degli atti di sindacato ispettivo e di indirizzo” (flag) – il funzionamento è come quello per l’abbinamento delle MOZ

**Comment by matteocattapan** [comment]
[#446](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/issues/446)
