### ISSUE TITLE
DASI: CONTROLLO ITL ORALI

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#456]
Decide UOLA l’iscrizione in seduta, nessun controllo del SW lato Consiglieri.

Gli altri tipi di ITL non vanno in Aula (quindi sarebbe auspicabile togliere il tasto “Iscrivi” per UOLA su ITL scritte e in commissione)

**Comment by ConsiglioRegionaleLombardia** [comment]
OK ma le ITL orali possono essere iscritte in Aula da UOLA anche quando sono nello stato "in trattazione". Attualmente nello stato "in trattazione" non è possibile effettuare l'iscrizione in seduta in "modalità singola" ma è possibile tramite comando massivo
