### ISSUE TITLE
DASI: CONTROLLO IQT

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#457]
Possono essere depositate dai consiglieri dalla data di inserimento della seduta (quindi appena UOLA inserisce la seduta nel sistema) e fino alla data di scadenza presentazione (poi vengono marcate fuori termine)

SW: Quando il consigliere clicca su “Proponi iscrizione a seduta” nel pannello a scorrimento verranno visualizzate solo le sedute NON CHIUSE (con data chiusura vuota o con data chiusura futura) e con flag “Seduta dedicata agli ATTI…” spuntato.

Nota: Le IQT non appaiono automaticamente in homepage e “Entrando in Aula” nelle “sedute proposte” dal consigliere, compaiono solo quando UOLA le ha inserite effettivamente in una seduta

**Comment by ConsiglioRegionaleLombardia** [comment]
OK. Il flusso IQT dalle ultime prove sembra corretto
