### ISSUE TITLE
DASI: CONTROLLO MOZ ORDINARIE

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#458]
Possono essere depositate dai consiglieri in qualsiasi momento e iscritte (proposta di iscrizione) nelle sedute NON CHIUSE appena UOLA inserisce la seduta nel sistema e fino alla data di scadenza presentazione (poi vengono marcate fuori termine inteso come proposta di iscrizione a seduta effettuata fuori tempo. Messaggio: “Richiesta di iscrizione effettuata fuori termine”)

SW: Quando il consigliere clicca su “Proponi iscrizione a seduta” nel pannello a scorrimento verranno visualizzate solo le sedute NON CHIUSE (con data chiusura vuota o con data chiusura futura) e con flag “Seduta dedicata agli ATTI…” spuntato.

Nota: si possono iscrivere in seduta sia moz nuove sia moz depositate da mesi. Le MOZ non appaiono automaticamente in homepage e “Entrando in Aula” nelle “sedute proposte”, compaiono solo quando UOLA le ha inserite effettivamente in una seduta.

**Comment by ConsiglioRegionaleLombardia** [comment]
ok. La proposta di iscrizione in seduta la può fare solo il capogruppo: è stato aperto un altro ticket
