### ISSUE TITLE
DASI: CONTROLLO MOZ URGENTI

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#459]
Possono essere depositate dai consiglieri in qualsiasi momento. L’urgenza può essere richiesta dal capogruppo dalla data della seduta vale a dire dalle 00:01 della “data seduta”  (quindi si controlla la DATA SEDUTA inserita a sistema) e fino alla data di scadenza presentazione (poi vengono marcate fuori termine inteso come richiesta di urgenza effettuata fuori tempo).

SW: Quando il capogruppo clicca su “Proponi urgenza” non vede nulla fino al giorno della seduta (sarebbe auspicabile prevedere un messaggio: “Attendi l’inizio della seduta per chiedere la trattazione d’urgenza”). Alle 00:01 del giorno della seduta comparirà la data nel pannello a scorrimento e sarà attiva fino alla data/ora di CHIUSURA SEDUTA (per rendere possibile il “fuori termine” inteso come “Richiesta d’urgenza effettuata fuori termine”). Dopo tale orario la seduta sparisce dal pannello di selezione dell’urgenza.

Nota: si possono iscrivere come urgenti sia moz nuove sia moz depositate da mesi. Le MOZ urgenti non appaiono automaticamente in homepage e “Entrando in Aula” nelle “sedute proposte”, compaiono solo quando UOLA le ha inserite effettivamente in seduta

**Comment by ConsiglioRegionaleLombardia** [comment]
L'**URGENZA** di una mozione può essere richiesta anche per le sedute **NON** dedicate alla trattazione di atti di indirizzo e sindacato ispettivo. Nel pannello per richiedere l'urgenza quindi alle 00:01 del giorno di una **qualsiasi** seduta aperta comparirà la data nel pannello a scorrimento e sarà attiva fino alla data/ora di CHIUSURA SEDUTA.

PROBLEMA **NON BLOCCANTE** AI FINI DEL COLLAUDO
