### ISSUE TITLE
DASI: CONTROLLO MOZ ABBINABILI

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#460]
Una moz può essere abbinata solo con una MOZ iscritta da UOLA nelle sedute CONVOCATE (data/ora apertura >= “a ora”) e che siano NON CHIUSE. Si tratta quindi di sedute “aperte” (come PEM). Si possono presentare fino alla data di scadenza presentazione (poi vengono marcate fuori termine con messaggio “Richiesta di abbinamento effettuata fuori termine”)

SW: Quando il capogruppo clicca sul bottone “Proponi abbinamento” nel menù a tendina verranno visualizzate solo le MOZ iscritte da UOLA in sedute NON CHIUSE (con data chiusura vuota o con data chiusura futura) E CONVOCATE (data_apertura >= “a ora”)

Nota: si possono abbinare sia moz nuove sia moz depositate da mesi. Le MOZ a cui abbinare non appaiono automaticamente, compaiono solo quando UOLA le ha inserite effettivamente in seduta.

**Comment by ConsiglioRegionaleLombardia** [comment]
La selezione delle mozioni non funziona correttamente: è stato effettuato un test iscrivendo 8 mozioni in una seduta ma nella selezione per l'abbinamento ne apparivano solo 4
