### ISSUE TITLE
DASI: CONTROLLO ODG

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#461]
I consiglieri possono presentare ODG solo per i PDL/Argomenti che si trovano in una seduta CONVOCATA (data/ora apertura >= a ora) che sia NON CHIUSA. Si tratta quindi di sedute “aperte” (come PEM). Ogni consigliere può presentare in questa fase 5 ODG per atto come primo firmatario. Gli ODG si possono presentare fino alla “data di scadenza presentazione” (poi vengono marcati fuori termine, fino a 5 ODG per atto. Dal sesto non si possono inserire più odg: il sesto viene bloccato dal sistema: questa regola vale anche per i capigruppo).

SW: Quando il consigliere crea un ODG può selezionare dal menu a tendina degli Atti/Argomenti presente nel form di inserimento solo gli Atti/Argomenti che si trovano in una seduta CONVOCATA (data/ora apertura >= a ora) che sia NON CHIUSA. Dopo la data scadenza di presentazione degli ODG, gli Atti/Argomenti continuano rimanere nella tendina di selezione e il sistema marcherà gli ODG presentati come fuori termine (fino al quinto per atto/argomento e per primo firmatario)

I capigruppo possono presentare, come primo firmatario, ulteriori 3 odg per atto dalla data della seduta vale a dire dalle 00:01 della “data seduta”  (quindi si controlla la DATA SEDUTA inserita a sistema) e fino alla chiusura della discussione generale di ogni singolo Atto/Argomento (poi vengono bloccati: non si possono aggiungere odg per lo specifico atto)

SW: Quando il consigliere crea un ODG può selezionare dal menu a tendina degli Atti/Argomenti solo gli Atti/Argomenti che si trovano in una seduta CONVOCATA (data/ora apertura >= a ora) che sia NON CHIUSA. Quando si conclude la discussione generale di un atto (Flag BloccoODG spuntato) quell’Atto/Argomento non apparirà più nel menù a tendina e non sarà più selezionabile (ovvero non si possono più inserire ODG riferiti a quell’Atto/Argomento).

Nota: Per inserire un ODG deve essere presente un Atto/Argomento/ in una seduta aperta e non conclusa.

**VEDI COMMENTI SOTTO**

**Comment by ConsiglioRegionaleLombardia** [comment]
Non funziona il blocco dopo 5 ODG per consigliere/atto. La specifica è la seguente:
Ogni consigliere può presentare in questa fase 5 ODG per atto come primo firmatario. Gli ODG si possono presentare fino alla “data di scadenza presentazione” (poi vengono marcati fuori termine, fino a 5 ODG per atto. Dal sesto non si possono inserire più odg: il sesto viene bloccato dal sistema: questa regola vale anche per i capigruppo).

Non funziona anche questo punto:
SOLO i capigruppo possono presentare, come primo firmatario, ulteriori 3 odg per atto dalla data della seduta vale a dire dalle 00:01 della “data seduta” (quindi si controlla la DATA SEDUTA inserita a sistema) e fino alla chiusura della discussione generale di ogni singolo Atto/Argomento (poi vengono bloccati: non si possono aggiungere odg per lo specifico atto): ADESSO IL SISTEMA NON BLOCCA DOPO IL LIMITE DEI 3 ODG (quindi ne riescono a presentare anche 4) E PERMETTE ANCHE AI CONSIGLIERI "NORMALI" DI PRESENTARE ODG IN QUESTA FASE (CHE NON VENGONO NEANCHE MARCATI FUORI TERMINE)
