### ISSUE TITLE
DASI: ODG-8.a evidenziare diversamente gli atti del proponente

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#468]
Colorare in maniera diversa gli atti di cui è proponente il consigliere collegato alla piattaforma. Utilizzare come sfondo dell'header il colore dell'atto molto lighting

**Comment by matteocattapan** [comment]
Ho mediato mettendo un icona nella griglia per il proponente collegato.

**Comment by ConsiglioRegionaleLombardia** [comment]
L'icona non è molto gradevole. Sarebbe meglio sottolineare il NOME del PROPONENTE oppure cerchiare il nome del proponente (grafica come il numero di atto nella griglia di lavoro di UOLA)
