### ISSUE TITLE
DASI: Ritiro ITR 

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#475]
Il ritiro dell'intero atto ITR da parte del primo firmatario deve essere consentito fino alla chiusura dell'atto (quindi sia in stato depositato sia in stato trattazione). Attualmente consente solo il ritiro della firma ma deve essere consentito anche il ritiro di tutto l'atto

Il ritiro deve essere possibile fintanto che l’atto non è chiuso. Quando un atto è in stato “Chiuso”, non si può più fare niente: né aggiungere firme, ne ritirare firme, né ritirare, né inviare a firmare.

Utilizzando la funzionalità “ritiro atto” l’Atto deve andare in stato “Chiuso - Ritirato” e le firme non vengono alterate ovvero non devono essere barrate

**Comment by matteocattapan** [comment]
risolto in #436
