### ISSUE TITLE
DASI: Visualizzazione griglia atti "sballata"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#477]
La colonna con in comandi (stampa, modifica, ecc) risulta "sballata"

![image](https://user-images.githubusercontent.com/57402160/197001776-4e14cb7a-83c8-41d6-b3a8-67d2da4350ee.png)

**Comment by matteocattapan** [comment]
Risolto in altri ticket
