### ISSUE TITLE
PEM: BUG su gestione utenti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#503]
Dopo aver effettuato la ricerca di un utente la piattaforma va in errore:
![image](https://user-images.githubusercontent.com/57402160/201305478-7b78ada1-8569-4448-8669-edd33dcfb599.png)

**Comment by matteocattapan** [comment]
#502

**Comment by ConsiglioRegionaleLombardia** [comment]
Problema non presente sulla nuova versione che andrà a breve in produzione sostituendo il branch master
