### ISSUE TITLE
Cambio di proponente a seguito di ritiro firma primo firmatario

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#525]
Quando il primo firmatario ritira la propria firma e ci sono altri firmatari che rendono l’atto ancora valido (c’è il numero necessario di firme, se richiesto), l’atto non va in stato “ritirato” ma risulta imputato al firmatario successivo e il sistema deve modificare automaticamente il proponente dell’atto. Il nuovo proponente sarà il “secondo firmatario valido” – Vedi art 10, comma 1, ultimo periodo, DUP 140/2020

**Comment by matteocattapan** [comment]
@ConsiglioRegionaleLombardia se il consigliere firmatario successivo valido è di un altro gruppo politico, questo può creare problemi?
Cambiando proponente, cambia anche il gruppo dell'atto.

**Comment by ConsiglioRegionaleLombardia** [comment]
No, non crea problemi. L'atto rimarrà visualizzato nell'area privata del proponente originale mentre il secondo firmtaari, ora nuovo proponete, continuerà a vederlo nell'area inviti.
Se queto dovesse creare problematiche con i controlli dei tasti funzione (ritira, ecc) si può cambiare l'id del gruppo politico dell'atto sul db per far diventare l'atto del nuovo gruppo


Inviato dal mio Galaxy


-------- Messaggio originale --------
Da: Matteo Cattapan ***@***.***>
Data: 16/12/22 19:05 (GMT+01:00)
A: Consiglio-Regionale-della-Lombardia/PEM ***@***.***>
Cc: Pagliaro Massimiliano ***@***.***>, Mention ***@***.***>
Oggetto: Re: [Consiglio-Regionale-della-Lombardia/PEM] Cambio di proponente a seguito di ritiro firma primo firmatario (Issue #525)


@ConsiglioRegionaleLombardia<https://github.com/ConsiglioRegionaleLombardia> se il consigliere firmatario successivo valido è di un altro gruppo politico, questo può creare problemi?
