### ISSUE TITLE
Funzionalità notifiche

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#53]
Se possibile mettere una spunta o uno sfondo verde o il testo in verde sulle notifiche quando il consigliere ha firmato l'emendamento

**Comment by matteocattapan** [comment]
Non ho ben capito dove mettere lo sfondo verde

**Comment by ConsiglioRegionaleLombardia** [comment]
Nell'area notifiche, dove c'è la lista delle notifiche.
Si tratta di mettere una spunta o colorare di verde le scritta o lo sfondo delle intestazioni delle notifiche qualora il consigliere abbia firmato l'em
![image](https://user-images.githubusercontent.com/57402160/126514632-8f440f71-f873-4761-9788-91495c9d69da.png)

**Comment by matteocattapan** [comment]
Esempio:
ci sono 5 inviti per l'em X di 2 hanno già firmato 
Soluzione 1 => 2/5
Soluzione 2 => 2 (pallino verde) - 3 (pallino blu)

**Comment by ConsiglioRegionaleLombardia** [comment]
La "spunta verde" dovrà essere visualizzata SOLO se il consigliere collegato e destinatario dell'invito ha firmato. Quello che fanno gli altri invitati non influirà sulla funzionalità.
La spunta sarà attiva solo sugli inviti ricevuti. Gli inviti mandati non avranno questa funzione
