### ISSUE TITLE
Flusso "fuori termine"

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#533]
Quando viene effettuata, fuori termine, la richiesta di iscrizione ad una seduta di una mozione, il sistema deve visualizzare l’avviso: “Richiesta di iscrizione effettuata fuori termine: procedere comunque?”. Nel caso il consigliere proceda, la richiesta viene accettata dal sistema e la “solita” icona “triangolo rosso” nelle griglie indicherà la richiesta è stata effettuata fuori termine. Nell’oggetto della notifica inviata dal sistema a UOLA deve essere aggiunta la scritta “ – FUORI TERMINE”.

Quando viene effettuata, fuori termine, la richiesta di urgenza di una mozione, il sistema deve visualizzare l’avviso: “Richiesta di trattazione urgente effettuata fuori termine: procedere comunque?”. Nel caso il capogruppo proceda, la richiesta d’urgenza viene accettata e la “solita” icona “triangolo rosso” nelle griglie indicherà la richiesta effettuata fuori termine. Nell’oggetto della notifica inviata dal sistema a UOLA deve essere aggiunta la scritta “ – FUORI TERMINE”.

**Comment by matteocattapan** [comment]
@ConsiglioRegionaleLombardia 
non sono stati indicati i campi "oggetto" e "corpo" della mail.
Verrà aperto un successivo incidente per aggiungere questi particolari.

**Comment by ConsiglioRegionaleLombardia** [comment]
I campi "oggetto" e "corpo" della email rimangono gli stessi presenti nella notifica inviata quando la richiesta è stata fatta nei termini. Nel solo oggetto dell'email inviate per richieste effettuate fuori termine va aggiunto (in fondo all'oggetto "di default") la scritta "- FUORI TERMINE"
Apriamo comunque un nuovo incident per aggiornare queste info
Grazie.

**Comment by matteocattapan** [comment]
> I campi "oggetto" e "corpo" della email rimangono gli stessi presenti nella **notifica inviata quando la richiesta è stata fatta nei termini**. Nel solo oggetto dell'email inviate per richieste effettuate fuori termine va aggiunto (in fondo all'oggetto "di default") la scritta "- FUORI TERMINE" Apriamo comunque un nuovo incident per aggiornare queste info Grazie.

Non viene mandata nessuna mail per la proposta urgenza nei termini, probabilmente state confondendo le procedure.
Rimango in attesa del nuovo incident per aggiungere il corpo e oggetto corretto nella procedura di invio mail con proposta urgenza.

A presto
