### ISSUE TITLE
DASI: @ITR-25 "tasto operazioni massive"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#580]
Dopo aver effettuato un deposito massivo, rimane il tasto per le operazioni massive e non torna il tasto + per aggiungere atti: è necessario il reload della pagina per effettuare un nuovo inserimento. Dovrebbe tornare automaticamente il tasto + per l’inserimento

**Comment by matteocattapan** [comment]
resettare la selezione in caso di azione Presenta
