### ISSUE TITLE
PEM: Spostamento multiplo EM

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#590]
![image](https://user-images.githubusercontent.com/57402160/208893319-60075219-65e3-42ff-933c-72ec27c11d1b.png)

Se sono selezionati più EM e si effettua uno spostamento per l'ordinamento, il sistema si blocca senza restituire messaggi

**Comment by matteocattapan** [comment]
Risolto con nuova visualizzazione
#553
