### ISSUE TITLE
PEM: Errore in em firmati d'ufficio

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#610]
Tentando di firmare d'ufficio un emendamento viene restituito un errore:
![image](https://user-images.githubusercontent.com/57402160/213203661-ac9c11d0-6cba-480c-9888-25d2b2f3372d.png)

**Comment by matteocattapan** [comment]
Trovato il problema
![image](https://user-images.githubusercontent.com/75838323/215159275-b6704de4-0f8f-4186-ba46-6e331d6193e1.png)


@ConsiglioRegionaleLombardia 
Che area politica prende la firma d'ufficio?
