### ISSUE TITLE
PEM: Visualizzazione EM all'interno del PDL

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#622]
Si è persa la formattazione delle chips degli emendamenti/subemendamenti all'interno del PDL:
![image](https://user-images.githubusercontent.com/57402160/214084961-3627ea44-1ed5-4f03-a921-9c0438553339.png)

**Comment by matteocattapan** [comment]
Risolto in #623
