### ISSUE TITLE
DASI: @EVO-8 "Stampe privacy"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#631]
Per UOLA anche la stampa immediata all'interno dell'atto deve chiedere il tipo di stampa: "Privacy" | "Originale"
![image](https://user-images.githubusercontent.com/57402160/214602394-11d5670d-e25b-4541-8c6c-900e143f763b.png)

Inoltre pare non sia gestito il campo OGGETTO per Privacy che è necessario in quanto:
- Quando viene modificato l'oggetto la modifica deve apparire solo nella griglia ma nell'atto e nelle stampe deve risultare l'oggetto originale
- Quando viene modificato l'oggetto "per motivi di privacy" deve essere visualizzato sempre l'oggetto offuscato per privacy (a video, nelle stampe ecc). Rimane per UOLA la possibilità di stampare l'atto originale

NOTA: per tutti gli altri utenti il sistema deve sempre visualizzare/stampare l'atto con il testo e l'oggetto modificati per privacy. Solo UOLA può vedere l'originale

**Comment by matteocattapan** [comment]
Gestione campo oggetto:

- Originale visualizzato su tutta la piattaforma
- Modificato visualizzato solamente nelle griglie per agevolare la visualizzazione nel client
- Modificato/Privacy visualizzato su tutta la piattaforma

NB solo UOLA e il proponente/creatore possono stampare l'originale in caso sia stato modificato per privacy l'oggetto
