### ISSUE TITLE
DASI: Problema con pannello bozze

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#658]
Cliccando sul pannello "BOZZE" (utenza consigliere), spariscono tutti i tab BOZZE|DPOSITATI|IN TRATTAZIONE|CHIUSI
![image](https://user-images.githubusercontent.com/57402160/216061303-73c4906f-54ab-437c-a08f-d3d6b738e6b2.png)

**Comment by matteocattapan** [comment]
Ho verificato in pem1 e funziona correttamente.

**Comment by ConsiglioRegionaleLombardia** [comment]
Ho riprovato ma il problema permane: entro come consigliere, clicco sul tab BOZZE e come in figura:
- vengono visualizzati gli atti in tutti gli stati (non solo le bozze)
- sparisce il TAB per visualizzare gli stati "BOZZE"|"DEPOSITATI"|"IN TRATTAZIONE"

Per scrupolo ho riprovato con EDGE e **funziona**. Il problema quindi è limitato a Chrome: ho provato anche con un Ctrl-shift-R, ma non si risolve. Verifico su altri pc per capire se il problema è limitato al mio client

#AGGIORNAMENTO:
Ho notato questa cosa strana: nel pannello per il filtro mancano gli stati bozza e bozza ris:
![image](https://user-images.githubusercontent.com/57402160/217204621-afd142c4-6d53-4af0-8e79-8fb53ef90d8b.png)

Se uso EDGE invece ci sono!
![image](https://user-images.githubusercontent.com/57402160/217204733-22fb02aa-2f45-420e-8187-158df51db144.png)

Rifatto Ctrl-shift-R ma non cambia nada

**Comment by matteocattapan** [comment]
Al login scarica tutta la sessione.
