### ISSUE TITLE
PEM e DASI: Allegato non presente nelle stampe

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#660]
A differenza della prima versione di pem, non vengono inseriti gli allegati nelle stampe.
Soprattutto per gli atti di sindacato ispettivo inseriti cartacei questo crea un problema per la pubblicazione. 
Andrebbe inserito nelle stampe anche l'allegato come in PEM v.1.0

**Comment by matteocattapan** [comment]
Aggiungere gli allegati all'interno del file pdf con IronPDF
