### ISSUE TITLE
PEM: Errore entrando negli emendamenti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#695]
Come segreteria dell'assemblea/amministratore, entrando nell'elenco degli emendamenti viene restituito un errore generico:
![image](https://user-images.githubusercontent.com/57402160/225074933-870d37f5-2afe-4612-9f73-885a1f218e8f.png)

**Comment by matteocattapan** [comment]
@ConsiglioRegionaleLombardia 
Creata la tabella "Tags" nel database l'errore non si presenta più
