### ISSUE TITLE
PEM: Errore nelle stampe

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#697]
Provando a fare la stampa singola di un emendamento viene restituito l'errore
![image](https://user-images.githubusercontent.com/57402160/225076821-2a3d7af5-cc16-433c-a337-7cf9519a3e05.png)

**Comment by matteocattapan** [comment]
![image](https://user-images.githubusercontent.com/75838323/225330486-c60f7fa9-96bc-4faf-984a-3c2b3302f2f6.png)
"Enable 32 bit Application" deve essere settato a False, altrimenti il componente IronPDF crasha.
