### ISSUE TITLE
DASI: Estrazione excel con firmatari mancanti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#699]
Estraendo il file excel per l'import in geasi, mancano diversi firmatari
![image](https://user-images.githubusercontent.com/57402160/225091159-ca260eff-3875-4c90-a3dd-3ef714df57d0.png)

**Comment by matteocattapan** [comment]
[download-1678878337895.xlsx](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/files/10978896/download-1678878337895.xlsx)

**Comment by matteocattapan** [comment]
Risolto grazie al ticket #698
