### ISSUE TITLE
DASI: Blocco della piattaforma in seguito a tentativo di abbinamento mozione

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#713]
Provando ad abbinare una mozione ad un'altra mozione, l'abbinamento non riesce e tutta la parte DASI va in errore.

**Comment by matteocattapan** [comment]
Controllo lato API e controllo lato client nel caso non ci siano mozioni da abbinare
