### ISSUE TITLE
PEM: Alert "EM presentato oltre i termini" nell'area Gruppi Politici

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#717]
Nell'area riservata ai Gruppi (sia come profilo segreteria sia come profilo consigliere) NON compare più l'alert (triangolo rosso con punto esclamativo) che indica che l'emendamento/subemendamento è stato presentato oltre i termini (12.30 del lunedì)
Nella workinglist di UOLA invece l'alert compare correttamente

**Comment by matteocattapan** [comment]
E' di colore bianco, lo coloro di rosso così torna normale
![Image](https://user-images.githubusercontent.com/75838323/229538791-21495c2f-6b88-4923-bcfb-a8237c4137ab.png)
