### ISSUE TITLE
DASI: Responsabile di segreteria e segreteria politica non possono mai firmare

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#726]
Il Responsabile di segreteria politica e la segreteria politica non possono mai firmare nessuna tipologia di atto: va quindi tolto il tasto firma per questi ruoli:
![image](https://user-images.githubusercontent.com/57402160/233572430-3e80644c-58d8-4722-8fb0-c147a8548bc2.png)

**Comment by matteocattapan** [comment]
#721
