### ISSUE TITLE
DASI: Modifica di un atto

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#735]
Gli atti modificati permangono in stato "di modifica" dopo essere stati salvati.

**Comment by matteocattapan** [comment]
Si esatto funziona così, come anche per gli atti Dasi funziona nella stessa maniera. Se si richiede una gestione differente, possiamo aggiungerlo come nuova feature.

**Comment by ConsiglioRegionaleLombardia** [comment]
In realtà in PEM dopo aver salvato, a seguito di una modifica, l'atto torna in stato "sola lettura". Mentre negli atti DASI, dopo il salvataggio, l'atto rimane nello stato "modifica". Il comportamento è diverso e sembra che il salvataggio non sia stato effettuato
