### ISSUE TITLE
DASI: Back da notifica

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#736]
Se si visualizza un atto, arrivato tramite invito, premendo il tasto per tornare indietro il sistema riporta nell'elenco degli atti mentre sarebbe corretto se tornasse alle notifiche

**Comment by matteocattapan** [comment]
Al momento il client torna indietro direttamente agli atti, se necessario, apriamo una richiesta di nuova feature

**Comment by ConsiglioRegionaleLombardia** [comment]
Si, va effettuata una sistemazione considerato che l'usabilità ne risente
