### ISSUE TITLE
DASI: Errore sul pannello "In trattazione"

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#737]
Con l'utente Segreteria, viene restituito un errore generico cliccando sul pannello "In trattazione" (a volte solo se si clicca una seconda volta):
![image](https://user-images.githubusercontent.com/57402160/235667204-4a42fc32-8d74-4094-acfe-bb1a6d9c4b6d.png)
**Il problema si verifica in PROD ma non in ambiente di test**

**Comment by ConsiglioRegionaleLombardia** [comment]
Problema dovuto alla mancanza del record relativo ad un nuovo consigliere nella tabella join_persona_AD.
Per evitare l'errore si propone la modifica in grassetto alla view_Consiglieri_in_carica:


SELECT DISTINCT 
                      ut.cognome + ' ' + ut.nome + ' (' + COALESCE (dbo.get_NomeGruppo_from_GUID(dbo.get_GUIDgruppoAttuale_from_persona(p.UID_persona)), '--') + ')' AS DisplayName, ut.UID_persona
FROM         dbo.join_persona_organo_carica AS jpoc INNER JOIN
                      dbo.persona ON jpoc.id_persona = dbo.persona.id_persona **INNER JOIN**
                      dbo.join_persona_AD AS p ON jpoc.id_persona = p.id_persona LEFT OUTER JOIN
                      dbo.View_UTENTI AS ut ON p.UID_persona = ut.UID_persona
WHERE     (jpoc.id_legislatura = dbo.get_legislatura_attuale()) AND (jpoc.deleted = 0) AND (ut.deleted = 0) AND (dbo.persona.deleted = 0) AND (jpoc.id_organo IN
                          (SELECT     id_organo
                            FROM          dbo.organi
                            WHERE      (id_legislatura = dbo.get_legislatura_attuale()) AND (id_tipo_organo <> 4) AND (deleted = 0))) AND (jpoc.data_inizio <= GETDATE()) AND (jpoc.data_fine >= GETDATE()) OR
                      (jpoc.id_legislatura = dbo.get_legislatura_attuale()) AND (jpoc.deleted = 0) AND (dbo.persona.deleted = 0) AND (jpoc.id_organo IN
                          (SELECT     id_organo
                            FROM          dbo.organi AS organi_1
                            WHERE      (id_legislatura = dbo.get_legislatura_attuale()) AND (id_tipo_organo <> 4) AND (deleted = 0))) AND (jpoc.data_inizio <= GETDATE()) AND (jpoc.data_fine IS NULL)

**Comment by ConsiglioRegionaleLombardia** [comment]
Aggiunto sul db il seguente trigger:
USE [dbEmendamenti]
GO

/****** Object:  Trigger [dbo].[Insert_persona]    Script Date: 05/02/2023 15:27:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		MP
-- Create date: 02/05/2023
-- Description:	Aggiunge un record contenete la login di rete (calcolata come nome.cognome - che non è sempre vero) alla tabella join_persona_AD quando si verifica una insert nella tabella persona replicata dal sw GeCo
-- =============================================
CREATE TRIGGER [dbo].[Insert_persona]
   ON  [dbo].[persona] 
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE
		@id_persona int,
		@nome nvarchar(25),
		@cognome nvarchar(25),
		@UserAD nvarchar(50);
	
	SELECT @id_persona=INSERTED.id_persona from INSERTED;
	SELECT @nome=INSERTED.nome from INSERTED;
	SELECT @cognome=INSERTED.cognome from INSERTED;
	set @UserAD='CONSIGLIO\' + @nome + '.' + @cognome;
	
    insert into join_persona_AD(id_persona, UserAD) values (@id_persona, @UserAD)
    -- Insert statements for trigger here

END

GO
andrebbe riportato nel git

**Comment by matteocattapan** [comment]
Ok perfetto!
