### ISSUE TITLE
Spostare scarica documento 

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#775]
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/6e16c5f0-22a7-4e3f-8ef9-20dd4636916e)

**Comment by matteocattapan** [comment]
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/077ae2e9-170a-46e3-8dcb-6a49ea15e3e3)

**Comment by matteocattapan** [comment]
@ConsiglioRegionaleLombardia 

Proposta grafica



![Image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/dc123bb8-fb61-4258-abeb-c37e1dac94ab)

**Comment by ConsiglioRegionaleLombardia** [comment]
Se non si riesce a realizzare la grafica progettata va bene anche la nuova proposta, ma se possibile lascerei la data delle scadenze visibile e sostituirei la scritta "SCARICA" con "SCARICA IL TESTO DELL'ATTO"
La cosa importante è comunque che la visualizzazione sia responsive e si adatti correttamente sugli smartphone
