### ISSUE TITLE
Link pubblico emendamento non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#800]
Il link pubblico per visualizzare l'emendamento presente in opendata non funziona:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/bdb925d6-039a-4c3f-9308-0a6e2fb65ed7)

il link è:
https://pem.consiglio.regione.lombardia.it/public/em?id=0a0a858b-102e-439f-b677-952fe2b71081

**Comment by matteocattapan** [comment]
Sono stati eseguiti i seguenti test con risultato positivo:

https://pem.consiglio.regione.lombardia.it/public/em?id=101a4b25-0765-48b4-b559-0c6793f2383f
https://pem.consiglio.regione.lombardia.it/public/em?id=cda1244b-fce3-43f5-a7ad-a7e661ef43cc
https://pem.consiglio.regione.lombardia.it/public/em?id=58bb3467-a149-45ba-8338-97260b8a7489
https://pem.consiglio.regione.lombardia.it/public/em?id=71dce458-b4d4-4589-86ce-50180319984e
