### ISSUE TITLE
Attivazione parametri dei filtri per Amministratore/Segreteria assemblea

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#802]
Si chiede di impostare le combo-box di selezione, presenti nei filtri, in modo che si attivino quando si clicca sopra e non quando si passa sopra col mouse. Il comportamento "click" è attivo per il ruolo Consigliere e Segreterie politiche mentre per Amministratore e UOLA si ha il comportamento "onmouseover" che rende difficoltoso l'utilizzo.
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/e7afd456-9cfe-4729-ac50-cd7b9c4e7a53)

**Comment by matteocattapan** [comment]
Non è presente nessun evento onmouseover. 
Per info fare riferimento alla documentazione di materialize 
https://materializecss.com/select.html
