### ISSUE TITLE
Problema in modifica emendamenti da preview

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#803]
Modificando delle note di emendamenti in visualizzazione preview, il sistema si comporta in modo anomalo.
Se si cancella ad esempio una nota riservata su un emendamento, la nota viene inserita nell'emendamento successivo!
Nello screenshot la nota (.) era nell'EM 6, è stata cancellata ed è apparsa nell'EM7
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/a396123a-d2ea-4aaa-972a-d768d3d048c6)

**Comment by matteocattapan** [comment]
Il problema non si verifica. Molto probabilmente è un errore dell'utente.
