### ISSUE TITLE
Repository Emendamenti

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#806]
La cartella di emergenza contenente i PDF degli emendamenti depositati (D:\emendamenti) non viene aggiornata

**Comment by matteocattapan** [comment]
La funzionalità è stata sostituita dal job di quartz che stampa i documenti richiesti all'occorrenza.

**Comment by ConsiglioRegionaleLombardia** [comment]
Probabilmente riattivando il sistema di notifica si riattiva anche questa funzione che può essere utile in casi di emergenza. La notifica comunque potrebbe essere sufficiente.
