### ISSUE TITLE
Cartelle LOG

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#807]
E' necessario sistemare le cartelle dei log applicativi

**Comment by matteocattapan** [comment]
Al momento risultano già sistemati correttamente, avete necessita organizzative particolari?

**Comment by ConsiglioRegionaleLombardia** [comment]
No. Potrei sbagliarmi ma sembra che ci siano delle cartelle di log delle versioni precedenti della piattaforma. Se è così sarebbe meglio cancellarli in modo da trovare subito il log corretto. Se invece sono tutti log corretti, si può chiudere il ticket
