### ISSUE TITLE
Dati sporchi

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#809]
A seguito di una modifica intervenuta su un em in bozza, il campo NLettera viene popolato con il valore [vuoto] "" anzicè Null:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/8a8908c8-3a5f-4139-abba-4bd8c43acd68)

Questo crea problemi alla store di ordinamento automatico del fascicolo

**Comment by matteocattapan** [comment]
Intervento a DB settando il campo di default a ["VUOTO"], stessa cosa lato codice nella creazione della proprietà NLettera
