### ISSUE TITLE
Seleziona tutti non funzionante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#825]
Lato UOLA il flag seleziona tutti non funziona. Dopo aver fatto seleziona tutti, facendo una operazione massiva vengono indicati 0 atti interessati dall'azione

**Comment by matteocattapan** [comment]
Il problema sembra essere solo nel portale di test, mentre in locale non si verifica. 
Confidiamo che con l'aggiornamento v2023.8.11 venga risolta la situazione
