### ISSUE TITLE
Mozioni urgenti e IQT chiuse conteggiate erroneamente

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#826]
Le MOZ urgenti e le IQT chiuse vengono comunque considerate nel conteggio delle firme. Quando sono chiuse le mozioni urgenti e le IQT non devono essere considerate nel conteggio delle firme

**Comment by matteocattapan** [comment]
Lo stato CHIUSO indica che il ciclo di vita dell'atto termina e viene considerato come APPROVATO, mentre lo stato CHIUSO_DECADUTO/RITIRATO indicano che l'atto non deve essere considerato valido perchè decaduto per mancanza di firme oppure ritirato dal proponente.
