### ISSUE TITLE
Rimuovi iscrizione non funzionate

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#827]
Il bottone "Rimuovi iscrizione" dedicato al proponente non funziona. La seduta rimane sempre indicata

![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/3c749747-164f-4e80-bb48-7332e7a7bb26)

**Comment by matteocattapan** [comment]
![Image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/c280772f-46df-4e0f-84ce-1f4f1defb804)



![Image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/ad5985ad-90fa-4abc-8c14-c97b8b34261a)



![Image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/c82e7f84-b741-44c9-bc10-28e434fea201)



![Image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/de21bea4-85d5-45a0-892b-e229962234e2)

**Comment by matteocattapan** [comment]
Non viene riscontrato alcun errore nella procedura
