### ISSUE TITLE
Rimozione priorità su IQT in bozza

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#838]
Se si tenta di rimuovere (o aggiungere) una firma prioritaria a una IQT in bozza il sistema rieffettua il controllo dell'atto (se è depositabile) e non premette nè la rimozione nè l'aggiunta della priotità a una firma. L'atto rimane quindi bloccato.
Quando l'IQT è in bozza è meglio non verificare se l'atto è depositabile alla rimozione delle priorità in modo da sbloccare l'atto

**Comment by matteocattapan** [comment]
La modifica viene rifiutata. L'utente per sbloccare la situazione dovrà ritirare la firma bloccante.
