### ISSUE TITLE
Amministratore - Filtri di ricerca

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#84]
Mancano i filtri per ricercare gli utenti:
 Legislatura: se possibile di default quella corrente (filtro pre impostato)
 Cognome
 Ruolo
 Gruppo
 Solo attivi: true di default

**Comment by matteocattapan** [comment]
@ConsiglioRegionaleLombardia E' necessario un endpoint dalla intranet che restituisce una lista di username in base al **ruolo** e/o al **gruppo** forniti nella richiesta.

**Comment by matteocattapan** [comment]
GetUser_in_Group()
