### ISSUE TITLE
Amministrazione - Gestione Gruppo politici

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#85]
Manca la parte di gestione dei Gruppi politici: da copiare dal vecchio portale

**Comment by matteocattapan** [comment]
- controllo utenti incongruenti col DB
- icona su action-card con totale componenti da espandere
- visualizzare utenti con bollino
- pulsante sincronizza con AD
