### ISSUE TITLE
Estensione UX/UI filtri

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#851]
Dare visibilità ai filtri impostati nelle griglie riepilogative di PEM/DASI con delle "chip" riportanti i valori ricercati che facilitano l'esperienza degli utenti, con la possibilità di rimuovere il filtro. Per maggior chiarezza si riporta un esempio preso da un sito di e-commerce in cui vengono filtrati dei cellulari (vedi immagine)
I filtri, impostati tramite l’apposita barra laterale delle ricerche, verranno visualizzati nelle “chip” che saranno posizionate sopra le griglie degli emendamenti e degli ATTI S.I. (sia per UOLA/Admin sia per i Gruppi/Consiglieri);
                Premendo sulla x, il relativo filtro verrà disapplicato e l’elenco degli atti si aggiornerà di conseguenza;

![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/22d8bc50-4286-4fcb-8013-bbe15c67c65a)

**Comment by ConsiglioRegionaleLombardia** [comment]
Da sviluppare nel nuovo sistema GeDASI per quanto riguarda gli atti di sindacato e d'indirizzo. Per gli emendamenti verrà valutata l'evolutiva in futuro, dopo aver verificato il comportamento sugli atti S.I.
