### ISSUE TITLE
Preview di ODG in seduta non funzioante

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#874]
Nell'area "Trattazione Aula" richiedendo la visualizzazione di preview degli atti di tipo ODG (gli altri funzionano) non viene restituito nessun atto:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/32f299cb-8a74-4b9f-99a1-cea5ba1e8515)

**Comment by matteocattapan** [comment]
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/761d2ea0-d4ed-4d2c-9cfa-42b3478ed55c)

**Comment by ConsiglioRegionaleLombardia** [comment]
In griglia si vedono. In preview no...
