### ISSUE TITLE
Ingresso in homepage non richiesto

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#876]
Diversi utenti segnalano che il sistema, durante la normale operatività (es. predisposizione di un atto), riporta spesso alla homepage costringendo a rieffettuare tutti i passaggi per tornare al punto dove si stava lavorando.

**Comment by ConsiglioRegionaleLombardia** [comment]
Dopo aver effettuato un filtro per proponente il problema è sistematico e viene segnalato che non si riesce a firmare emendamenti. Purtroppo i numeri sono molto elevati e senza filtro, il problema è critico...

**Comment by matteocattapan** [comment]
Viene gestito nel #880
