### ISSUE TITLE
Campo NLettera non valorizzato correttamente

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#885]
In alcuni sporadici casi il campo di database Nlettera della tabella EM risulta "vuoto" anzichè "null" e questo provoca un comportamento errato della procedura di ordinamento automatico degli emendamenti
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/ec30d645-0dc4-48ec-95ec-31c85c45a092)

**Comment by matteocattapan** [comment]
#809
