### ISSUE TITLE
Chip IQT mancanti in homepage

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#907]
seduta del 16/10/24
7 IQT iscritte alla seduta
In homepage vengono contate correttamente 7 IQT ma ne sono elencate solo 5
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/2fac51bd-8da1-43c3-961c-d6cbc8f80150)

**Comment by ConsiglioRegionaleLombardia** [comment]
Ho verificato i dati ma non ho riscontrato problemi sulla tabella ATTI_DASI

**Comment by matteocattapan** [comment]
E' stato configurato il limite di visualizzazione a 5 perchè l'obiettivo era di tenere la dashboard leggera.
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/75838323/baac8e1c-0d30-4476-a702-f42fe0d5ddd5)

Come volete procedere?

**Comment by ConsiglioRegionaleLombardia** [comment]
Va bene il limite ma andrebbe impostato ad almeno 50 elementi (se non si rilevano problemi anche a 100, tenendo conto che solo gli ODG possono raggiungere questo limite, gli altri atti sono sempre inferiori a 20 per singola seduta).
L'ottimo inoltre sarebbe inserire una chip "... + altri" in caso si superi il limite dei (50-100) altrimenti l'impressione è che ci sia un bug nella piattaforma (che in realtà non c'è)
