### ISSUE TITLE
Problema nelle stampe del modulo PEM

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#910]
Generando una stampa in PEM, senza spuntare emendamenti, viene visualizzato l'errore:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/c7e2b798-f766-43e9-8e3a-a549b22194dc)

In mancanza di selezione, il comportamento corretto è invece quello di stampare tutti gli emendamenti presenti nella griglia. Il modulo DASI ha il comportamento corretto

**Comment by matteocattapan** [comment]
Per esigenze tecniche sarebbe necessario selezionare almeno "seleziona tutti".
DASI dopo la correzione del bug #912 riporta lo stesso comportamento.
