### ISSUE TITLE
Problema con selezionata tutti e paginazione a 250

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#913]
Quando la paginazione è a 250 elementi, il flag seleziona tutti manda in errore la procedura.
Se il problema è dovuto ad un limite tecnico e non è possibile aumentare la lunghezza della request, si potrebbe limitare in automatico la spunta del "seleziona tutti" ai primi 200 elementi.

**Comment by matteocattapan** [comment]
Al momento sembra essere dovuto a dei rallentamenti di rete e dalla procedura.
