### ISSUE TITLE
ERRORE (in test): Vengono depositati 6 odg per consigliere semplice

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#914]
Come da immagine al deposito massivo di 6 odg (dopo aver filtrato il pdl di riferimento) viene restituito l'errore in allegato:

![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/0bc13475-4c9f-4ccb-bd99-b34a3c01bc9a)

tuttavia vengono depositati 6 odg per il consigliere semplice:

![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/042a7570-ecba-4fb1-a82b-112664ea8cc5)

**Comment by ConsiglioRegionaleLombardia** [comment]
L'errore può essere anche il seguente:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/4be856f8-d6a6-4c6a-a896-b0ad3d3883ff)

Ma comunque permette di depositare più di 5 odg

**Comment by matteocattapan** [comment]
L'errore esposto è dovuto al fatto che il servizio SmartSMTP non funziona, quindi non riesce a mandare le mail. Indago invece per le 6 odg

**Comment by matteocattapan** [comment]
Questa richiesta va in contrasto con la issue #889 rilasciata nella versione v2023.10.24.6.
Come si intende procedere?

**Comment by matteocattapan** [comment]
Confermiamo che la gestione della risoluzione del ticket #889 non era corretta, quindi viene reintegrato il codice precedente.
