### ISSUE TITLE
IQT: Problema priorità firme

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#937]
Si riscontra un'anomalia sulla IQT 1076 (ma lo stesso comportamento si ha con la 1077 e 1078): provando a togliere la priorità a un consigliere, **non influente al fine del calcolo delle firme**, viene restituito un errore che impedisce il ritiro della priorità e che riporta, erroneamente, che gli altri consiglieri non sono più validi.
Si segnala che l'IQT sono iscritte in seduta: potrebbe influire sulla verifica delle firme?

**Comment by matteocattapan** [comment]
Si, influisce
