### ISSUE TITLE
Deposito ITR: notifica non inviata

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#944]
Non vengono inviate le notifiche relative al deposito.
Sono stati effettuati alcuni test di deposito di ITR e nessuna notifica è stata recapitata.
Nella piattaforma di produzione il gruppo politico che ha depositato l'ITR ha un responsabile di segreteria dove non è stato inserito correttamente il gruppo di riferimento:
![image](https://github.com/Consiglio-Regionale-della-Lombardia/PEM/assets/57402160/7e75141d-4d07-4a6d-8343-b533e1e3823c)
Nella piattaforma di test il responsabile di segreteria del gruppo utilizzato per le prove non è presente.

Potrebbe essere questo il problema?

**Comment by ConsiglioRegionaleLombardia** [comment]
Si aggiunge che non è arrivata la notifica anche per la IQT 1906. Anche in questo caso non c'è un responsabile di segreteria configurato per ricevere notifiche.

Si chiede di verificare se la mancanza di un Responsabile di segreteria in quanto mancante o erroneamente configurato possa causare la mancata notifica al deposito.

**Comment by matteocattapan** [comment]
Si è perchè non viene indicato il gruppo di riferimento

Query:
"Select * from UTENTI_NoCons where id_gruppo_politico_rif={id}"
