### ISSUE TITLE
Mancato ricaricamento griglia dopo l'inserimento di un atto da parte di un responsabile del gruppo

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#952]
Se il responsabile di segreteria aggiunge un nuovo atto per un consigliere (che avviene in una nuova scheda del browser), alla chiusura della scheda non si aggiorna la griglia con gli atti nella scheda.parent.
Dal profilo "consigliere" invece funziona correttamente

**Comment by matteocattapan** [comment]
Verificato che non capita più questo problema
