### ISSUE TITLE
Filtro per Data seduta e Data iscrizione seduta non coerente

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#970]
Filtrando gli ODG per "data seduta" o per "data iscrizione seduta" il risultato non è corretto. Sembra che il filtro venga applicato sulla data di presentazione dell'ODG

**Comment by matteocattapan** [comment]
Il filtro funziona correttamente.
"Data seduta" filtra per data seduta (freccia rossa)
"Data iscrizione seduta" filtra per la data di iscrizione in seduta (freccia viola).

Esempio:
![Image](https://github.com/user-attachments/assets/75b8bd0b-11bd-4272-aa37-62195ebfa2ba)
