### ISSUE TITLE
Griglia: nomi e ordine colonne

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#989]
Si chiede di prevedere un ordinamento e una nomenclatura delle colonne della GRIGLIA di lavoro differente rispetto a quanto previsto per i report.
La griglia dovrebbe avere un ordinamento personalizzato e dei nomi di colonna funzionali alle attività di UOLA

**Comment by ConsiglioRegionaleLombardia** [comment]
Elenco ordinato delle colonne da prevedere nella griglia:

 1. Legislatura
 2. Tipo atto
 3. ATTO _(non selezionabile, sempre presente per entrare nelle CRUD dell'atto)_
 4. Tipo mozione
 5. Etichetta
 6. Oggetto
 7. Proponente
 8. Firmatari
 9. Data presentazione
10. Firme dopo il deposito
11. Gruppo politico _(del proponente)_
12. Firme ritirate
13. Area politica
14. Codice
15. Non passaggio all’esame
16. Commissioni _(visualizza le commissioni presenti nel monitoraggio o nella risposta per ITL e ITR o nella trattazione per MOZ e RIS)_
17. Commissioni proponente RIS
18. Note
19. Data annunzio
20. Data comunicazione all’Assemblea
21. Stato
22. Motivo chiusura
23. Data chiusura
24. Data seduta proposta
25. Data seduta
26. Tipo votazione
27. Emendato
28. DCR/DCCR
29. Impegni e scadenze
30. Giunta _(visualizza gli organi di Giunta presenti nella risposta per ITL, ITR, IQT)_
31. Tipo risposta richiesta
32. Tipo risposta fornita _(deve avere solo i valori: Scritta | Orale | In commissione)_
33. Iter multipli
34. N° gg di ritardo - _calcolato come Data risposta - Data Annunzio + 20 giorni. SE Data risposta è vuoto allora è calcolato come Oggi - Data Annunzio + 20 giorni (se, in entrambi i casi, il risultato è minore di 0 restituisce 0)_
35. Sollecito
36. Data trasmissione RIS _(è la data in cui la commissione trasmette la RIS all’assemblea per l’iscrizione in seduta. in GEASI 37. corrisponde al campo Data Trasmissione presente nel TAB "Trattazione in commissione" che compare solo nelle RIS)_
38. Conteggio firme
39. Privacy
40. Privacy - Divieto pubblicazione
41. Presentato oltre i termini

**Comment by ConsiglioRegionaleLombardia** [comment]
Vedi anche ticket #1052 #1049 #1048 #1075

**Comment by matteocattapan** [comment]
Non vengono trattati nella lista i seguenti campi:

- DataIscrizioneSeduta
- DataRitiro
- Premesse
- Richiesta
- StatoAttuazione
- CompetenzaMonitoraggio
- Protocollo
- Abbinamenti
- AreaTematica
- AltriSoggetti
- MonitoraggioConcluso
- DataTrasmissioneMonitoraggio
- Pubblicato
- Documenti
- BURL

**Comment by ConsiglioRegionaleLombardia** [comment]
DataIscrizioneSeduta (vedi sotto)
DataRitiro (vedi sotto)
Premesse - TOGLIERE
Richiesta - TOGLIERE
AltriSoggetti - TOGLIERE
CompetenzaMonitoraggio - TOGLIERE
AreaTematica - TOGLIERE

  6.**Abbinamenti**
15.**Protocollo**
16.**BURL**
42.**StatoAttuazione**
43.**AreaTematica**
44.**MonitoraggioConcluso**
45.**DataTrasmissioneMonitoraggio**
46.**Pubblicato**
47.**Documenti**


Per i seguenti campi:

- DataIscrizioneSeduta
- DataRitiro

nell'attuale piattaforma dati vengono visualizzati in tooltip sulla colonna DataSeduta e sulla colonna Stato (qualora lo stato sia CHIUSO-Ritirato).
Se nella nuova griglia non è possibile riprodurre il comportamento, Data iscrizione seduta va posizionato vicino a Data seduta (posizione 26) e DataRitiro vicino al Motivo Chiusura (posizione 23)

**Comment by ConsiglioRegionaleLombardia** [comment]
Mancano alcune colonne:
N° gg di ritardo
Commissioni
Giunta

Giunta potrebbe essere sostituito da "Informazioni risposte". Meglio però posizionarlo vicino a riposta richieste/risposta fornita

**Comment by matteocattapan** [comment]
Aprire un nuovo task, questo è chiuso

**Comment by ConsiglioRegionaleLombardia** [comment]
Si, già aperto il task in draft.
Ho solo aggiunto un commento a questa issue perché qui è spiegato meglio (la posizione delle colonne, ecc…)

Da: Matteo Cattapan ***@***.***>
Inviato: mercoledì 4 dicembre 2024 14:49
A: Consiglio-Regionale-della-Lombardia/PEM ***@***.***>
Cc: Pagliaro Massimiliano ***@***.***>; Author ***@***.***>
Oggetto: Re: [Consiglio-Regionale-della-Lombardia/PEM] Griglia: nomi e ordine colonne (Issue #989)


ATTENZIONE - MESSAGGIO ESTERNO - Non cliccare su link, non aprire allegati e non rispondere se non si è certi del mittente e della legittimità della richiesta.


Aprire un nuovo task, questo è chiuso
