### ISSUE TITLE
CRUD: gestione campi privacy

### ISSUE THREAD

**Issue by ConsiglioRegionaleLombardia** [Consiglio-Regionale-della-Lombardia/PEM#998]
![image](https://github.com/user-attachments/assets/06c86623-7a12-4daf-a833-71deba8388b4)

Le spunte "Privacy" e "Privacy - Divieto di pubblicazione" devono servire per abilitare/disabilitare i campi sottostanti

**Comment by matteocattapan** [comment]
Non è chiaro cosa devo fare. Potete essere più precisi sul da farsi?

**Comment by ConsiglioRegionaleLombardia** [comment]
La funzionalità necessaria è quella di avere dei flag relativi alla "privacy" che indicano se nell'atto sono presenti "dati personali semplici" e/o "dati sensibili" e/o "dati giudiziari".
Nella ricerca però deve essere possibile ricercare un atto modificato per "privacy" a prescindere dal motivo. Quindi selezionando Privacy=SI il sistema deve estrarre tutti gli atti che sono protetti da privacy ovvero se **almeno** uno dei flag "dati personali semplici" e/o "dati sensibili" e/o "dati giudiziari" è stato spuntato.

Per evitare errori è quindi necessario fare in modo che selezionando uno dei motivi: "dati personali semplici" e/o "dati sensibili" e/o "dati giudiziari", automaticamente si spunti il flag privacy che si suppone verrà utilizzato nella ricerca. Oppure il flag "Privacy" può essere utilizzato per abilitare/disabilitare i flag "dati personali semplici" e/o "dati sensibili" e/o "dati giudiziari".

La stessa cosa vale per la parte "Divieto di pubblicazione".

Attualmente in GEASI sono previsti solo i flag relativi ai motivi di privacy o di non pubblicabilità di un atto:
![image](https://github.com/user-attachments/assets/f01ea029-2c3d-41f1-87e7-92109e6536ee)

Infatti "Privacy" e "Divieto di pubblicazione" in GEASI sono solo delle etichette.

Da tenere anche in considerazione il fatto che, quando un testo presenta problemi di privacy, l'atto pubblicato in Internet tramite il ws è un atto modificato e caricato sempre attraverso la "Scheda Privacy" come in figura.
In gedasi invece si ipotizzava di gestire questa funzione nella scheda allegati.
